name: Deploy to Cloud Run via Artifact Registry

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Google Cloud credentials
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v1
      with:
        key-file: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Step 3: Set the Google Cloud project ID
    - name: Set project ID
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Configure Docker to use Artifact Registry
    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    # Step 5: Build Docker image and push to Artifact Registry
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gh-demo/flask-cloud-run:latest .
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gh-demo/flask-cloud-run:latest

    # Step 6: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-cloud-run \
          --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gh-demo/flask-cloud-run:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
